Repository State-Channel-4/Channel4-pocv2, pull requests merged in 2023-05, with the labels that each got.

#29 updated smart contract with tags and fetching data
  contracts/UrlContract.sol
Labels: backend

#34 Draft: replaced upvote and downvote with likes. Added swagger-ui docs
  backend/controllers/contractController.js
  backend/models/schema.js
  backend/package-lock.json
  backend/package.json
  backend/routes/contracts.js
  backend/server.js
  backend/swaggerOptions.js
Labels: documentation, enhancement, backend

#42 Feat/nico/migrate to next
  apps/poc-next/app/create-account/page.tsx
  apps/poc-next/app/discover/SiteFrame.tsx
  apps/poc-next/app/discover/page.tsx
  apps/poc-next/app/layout.tsx
  apps/poc-next/app/sign-up/page.tsx
  apps/poc-next/assets/bust-of-woman-with-flowers.svg
  apps/poc-next/assets/channel-4-icon-black.svg
  apps/poc-next/assets/channel-4-icon-v2.svg
  apps/poc-next/assets/channel-4-logo-v1.svg
  apps/poc-next/components/bottom-nav.tsx
  apps/poc-next/components/ui/tag-list.tsx
  apps/poc-next/config/site.ts
  apps/poc-next/lib/fonts.ts
  apps/poc-next/package.json
  apps/poc-next/pnpm-lock.yaml
  apps/poc-next/store/encrypted.ts
  apps/poc-next/store/wallet.ts
  apps/poc-next/tailwind.config.js
  contracts/contracts/UrlContract.sol
  contracts/test/UrlContract.ts
Labels: enhancement, frontend

#43 swagger docs and options file were missing. added. Now /docs route w…
  backend/package-lock.json
  backend/server.js
  backend/swaggerOptions.js
Labels: documentation, enhancement

#46 route /mix done. separate function to shuffle the urls and fetch url…
  backend/controllers/contractController.js
  backend/pnpm-lock.yaml
  backend/routes/contracts.js
  backend/swaggerOptions.js
Labels: enhancement, backend
